<div class="flex min-h-screen bg-surface dark:bg-ink transition-colors">
  <?php require __DIR__ . '/../partials/admin-sidebar.php'; ?>
  <main class="flex-1 px-8 py-8">
    <div class="mb-8"><h1 class="font-display font-semibold text-2xl text-ink dark:text-white">Seller settings</h1><p class="text-sm text-gray-500 dark:text-white/50">Manage your account and the public details of your shop.</p></div>
    <?php if ($success): ?><div class="max-w-2xl mb-5 rounded-xl bg-emerald-50 text-emerald-700 px-4 py-3 text-sm">Settings saved successfully.</div><?php endif; ?>
    <?php if ($error): ?><div class="max-w-2xl mb-5 rounded-xl bg-red-50 text-red-700 px-4 py-3 text-sm"><?= htmlspecialchars($error) ?></div><?php endif; ?>
    <?php if ($isInitialSetup): ?><div class="max-w-2xl mb-5 rounded-xl bg-amber-50 text-amber-800 px-4 py-3 text-sm">Complete your shop profile and submit your business proof. This is required for seller verification.</div><?php endif; ?>
    <form method="POST" action="/admin/settings/update" enctype="multipart/form-data" class="max-w-2xl space-y-6">
      <section class="bg-white dark:bg-ink-2 border border-gray-100 dark:border-white/10 rounded-2xl p-6 shadow-sm"><h2 class="font-display font-semibold text-base text-ink dark:text-white mb-4">Account details</h2><div class="grid sm:grid-cols-2 gap-4"><div><label class="block text-xs font-medium text-gray-500 mb-1.5">Full name</label><input required name="name" value="<?= htmlspecialchars($user['name'] ?? '') ?>" class="w-full rounded-xl border border-gray-200 px-3.5 py-2.5 text-sm"></div><div><label class="block text-xs font-medium text-gray-500 mb-1.5">Email</label><input required type="email" name="email" value="<?= htmlspecialchars($user['email'] ?? '') ?>" class="w-full rounded-xl border border-gray-200 px-3.5 py-2.5 text-sm"></div></div></section>
      <section class="bg-white dark:bg-ink-2 border border-gray-100 dark:border-white/10 rounded-2xl p-6 shadow-sm"><h2 class="font-display font-semibold text-base text-ink dark:text-white mb-4">Shop profile</h2><div class="space-y-4"><div><label class="block text-xs font-medium text-gray-500 mb-1.5">Shop name</label><input required name="business_name" value="<?= htmlspecialchars($application['business_name'] ?? '') ?>" class="w-full rounded-xl border border-gray-200 px-3.5 py-2.5 text-sm"></div><div><label class="block text-xs font-medium text-gray-500 mb-1.5">About your shop</label><textarea required name="business_description" rows="4" class="w-full rounded-xl border border-gray-200 px-3.5 py-2.5 text-sm"><?= htmlspecialchars($application['business_description'] ?? '') ?></textarea></div><div class="grid sm:grid-cols-2 gap-4"><div><label class="block text-xs font-medium text-gray-500 mb-1.5">Mobile number</label><input required name="phone" value="<?= htmlspecialchars($application['phone'] ?? '') ?>" class="w-full rounded-xl border border-gray-200 px-3.5 py-2.5 text-sm"></div><div><label class="block text-xs font-medium text-gray-500 mb-1.5">Business address</label><input required name="business_address" value="<?= htmlspecialchars($application['business_address'] ?? '') ?>" class="w-full rounded-xl border border-gray-200 px-3.5 py-2.5 text-sm"></div></div><div><label class="block text-xs font-medium text-gray-500 mb-1.5">Business logo</label><div class="flex items-center gap-4"><?php if (!empty($application['logo_path'])): ?><img src="/<?= htmlspecialchars($application['logo_path']) ?>" alt="Current shop logo" class="w-14 h-14 rounded-xl object-cover border border-gray-200"><?php endif; ?><input type="file" name="business_logo" accept="image/png,image/jpeg" <?= $isInitialSetup ? 'required' : '' ?> class="text-xs text-gray-500"><span class="text-xs text-gray-400"><?= $isInitialSetup ? 'Required: PNG/JPG, 5MB max.' : 'Optional: PNG/JPG, 5MB max.' ?></span></div></div><?php if ($isInitialSetup): ?><div><label class="block text-xs font-medium text-gray-500 mb-1.5">Business registration or valid proof</label><input required type="file" name="business_document" accept="application/pdf,image/png,image/jpeg" class="text-xs text-gray-500"><p class="text-xs text-gray-400 mt-1">DTI/SEC registration, barangay permit, or valid proof. PDF, PNG, or JPEG; 5MB max.</p></div><?php endif; ?></div></section>
      <button class="px-5 py-3 rounded-xl bg-brand text-white text-sm font-semibold hover:bg-brand-dark">Save changes</button>
    </form>
  </main>
</div>
