<div class="flex min-h-screen bg-gray-50 dark:bg-ink">
  <?php require __DIR__ . '/../../partials/admin-sidebar.php'; ?>
  <main class="flex-1 px-5 py-7 md:px-8">
  <h1 class="font-display text-2xl font-semibold text-gray-900">Allocate stock to branch</h1>
  <p class="mt-1 text-sm text-gray-500">Allocation moves stock from Seller Inventory to the selected branch. It does not use Seller POS stock.</p>
  <?php if (!empty($error)): ?><p class="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700"><?= htmlspecialchars($error) ?></p><?php endif; ?>
  <div class="mt-6 overflow-hidden rounded-lg border border-gray-200 bg-white"><table id="allocationsTable" data-datatable class="w-full text-sm"><thead><tr class="border-b text-left text-xs uppercase text-gray-500"><th class="p-3">Product / variant</th><th class="p-3">Seller inventory stock</th><th class="p-3">Allocate to branch</th></tr></thead><tbody>
  <?php foreach ($rows as $row): $available=(int)($row['size'] !== null ? $row['variant_stock'] : $row['stock']); if ($available < 1) continue; ?><tr class="border-b last:border-0"><td class="p-3 font-medium"><?= htmlspecialchars($row['name']) ?><?= $row['size'] !== null ? ' — '.htmlspecialchars($row['size'].' / '.$row['color']) : '' ?></td><td class="p-3"><span class="inline-flex items-center gap-1.5 rounded-full bg-blue-50 px-2.5 py-1 text-xs font-bold text-blue-700"><i data-lucide="warehouse" class="h-3.5 w-3.5"></i><?= $available ?> in inventory</span></td><td class="p-3"><form class="js-confirm-form flex flex-wrap items-center gap-2" data-title="Allocate stock to this branch?" data-text="This deducts the entered quantity from Seller Inventory and adds it to the selected branch." data-icon="question" data-confirm-text="Yes, allocate" data-confirm-color="#2563EB" method="post" action="/admin/allocations/store"><input type="hidden" name="product_id" value="<?= (int)$row['product_id'] ?>"><input type="hidden" name="variant_size" value="<?= htmlspecialchars($row['size'] ?? '') ?>"><input type="hidden" name="variant_color" value="<?= htmlspecialchars($row['color'] ?? '') ?>"><select required name="branch_id" aria-label="Destination branch" class="border rounded px-2 py-1.5"><option value="">Select branch</option><?php foreach($branches as $branch): ?><option value="<?= (int)$branch['id'] ?>"><?= htmlspecialchars($branch['name']) ?></option><?php endforeach; ?></select><div class="relative"><label class="sr-only" for="allocation-<?= (int)$row['product_id'] ?>-<?= (int)($row['id'] ?? 0) ?>">Stock quantity to allocate</label><i data-lucide="boxes" class="pointer-events-none absolute left-2 top-2 h-4 w-4 text-gray-400"></i><input id="allocation-<?= (int)$row['product_id'] ?>-<?= (int)($row['id'] ?? 0) ?>" required min="1" max="<?= $available ?>" type="number" name="quantity" placeholder="Qty" title="Stock quantity to allocate" class="w-24 border rounded py-1.5 pl-7 pr-2" aria-label="Stock quantity to allocate"></div><input name="note" placeholder="Allocation note (optional)" aria-label="Allocation note" class="border rounded px-2 py-1.5"><button class="inline-flex items-center rounded bg-teal px-3 py-1.5 text-white" type="submit"><i data-lucide="package-plus" class="mr-1.5 h-4 w-4"></i>Allocate stock</button></form></td></tr><?php endforeach; ?>
  </tbody></table></div></main></div>
