<div class="flex min-h-screen bg-gray-50">
  <?php require __DIR__ . '/../../partials/admin-sidebar.php'; ?>
  <main class="flex-1 px-8 py-8"><div class="max-w-xl"><a href="/stock-requests" class="text-sm text-gray-400">&larr; Back to stock requests</a><h1 class="mt-2 mb-6 font-display text-2xl font-semibold text-gray-900">New stock request</h1>
  <?php if (!empty($error)): ?><div class="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><?= htmlspecialchars($error) ?></div><?php endif; ?>
  <?php if (empty($supplies)): ?><div class="mb-5 rounded-lg border border-amber/30 bg-amber/10 px-4 py-3 text-sm text-amber-800">No available supplier supplies yet. Suppliers must add stock first.</div><?php endif; ?>
  <form method="POST" action="/stock-requests/store" class="space-y-5 rounded-lg border border-gray-200 bg-white p-6"><div><label for="supplier_id" class="mb-1.5 block text-xs font-medium text-gray-600">Supplier</label><select id="supplier_id" name="supplier_id" required class="w-full rounded-xl border border-gray-200 px-4 py-2.5 text-sm text-ink"><option value="">Select a supplier...</option><?php $supplierOptions=[]; foreach($supplies as $supply) $supplierOptions[$supply['supplier_id']]=$supply['supplier_name']; foreach($supplierOptions as $id=>$supplierName): ?><option value="<?= (int)$id ?>"><?= htmlspecialchars($supplierName) ?></option><?php endforeach; ?></select></div>
  <div><label for="supply_id" class="mb-1.5 block text-xs font-medium text-gray-600">Available supply</label><select id="supply_id" name="supply_id" required disabled class="w-full rounded-xl border border-gray-200 px-4 py-2.5 text-sm text-ink"><option value="">Choose a supplier first...</option><?php foreach($supplies as $supply): ?><option value="<?= (int)$supply['id'] ?>" data-supplier="<?= (int)$supply['supplier_id'] ?>" data-stock="<?= (int)$supply['quantity_available'] ?>" hidden><?= htmlspecialchars($supply['item_name']) ?> — ₱<?= number_format((float)$supply['unit_price'],2) ?>/<?= htmlspecialchars($supply['unit']) ?> (<?= (int)$supply['quantity_available'] ?> available)</option><?php endforeach; ?></select><p id="stock-help" class="mt-1 text-xs text-gray-500">Select a supplier to view their in-stock supplies.</p></div>
  <div><label for="quantity" class="mb-1.5 block text-xs font-medium text-gray-600">Quantity</label><input id="quantity" name="quantity" type="number" min="1" required placeholder="e.g. 50" value="<?= htmlspecialchars($_POST['quantity'] ?? '') ?>" class="w-full rounded-xl border border-gray-200 px-4 py-2.5 text-sm text-ink" /></div>
  <div><label for="note" class="mb-1.5 block text-xs font-medium text-gray-600">Note (optional)</label><textarea id="note" name="note" rows="3" placeholder="Any extra detail for the supplier..." class="w-full rounded-xl border border-gray-200 px-4 py-2.5 text-sm text-ink"><?= htmlspecialchars($_POST['note'] ?? '') ?></textarea></div><button type="submit" class="mt-2 w-full rounded-xl bg-ink py-3 text-sm font-medium text-white">Send request</button></form></div></main></div>
<script>
const supplierSelect=document.getElementById('supplier_id'),supplySelect=document.getElementById('supply_id'),stockHelp=document.getElementById('stock-help');
function filterSupplies(){const supplierId=supplierSelect.value;supplySelect.disabled=!supplierId;supplySelect.value='';for(const option of supplySelect.options){if(!option.value)continue;option.hidden=option.dataset.supplier!==supplierId;}stockHelp.textContent=supplierId?'Choose one of this supplier\'s available supplies.':'Select a supplier to view their in-stock supplies.';}
supplierSelect.addEventListener('change',filterSupplies);supplySelect.addEventListener('change',()=>{const option=supplySelect.selectedOptions[0];if(option?.value)stockHelp.textContent=`${option.dataset.stock} available.`;});
</script>
