<div class="flex min-h-screen bg-gray-50">
  <?php require __DIR__ . '/../partials/sidebar.php'; ?>
  <main class="flex-1 px-5 py-7 md:px-8">
    <header class="mb-6"><h1 class="font-display text-2xl font-semibold text-gray-900">My orders</h1><p class="mt-1 text-sm text-gray-500">Track your orders and cancel an order while it is still pending.</p></header>
    <?php if ($justPlaced): ?><div class="mb-5 rounded-lg border border-teal/30 bg-teal-light px-4 py-3 text-sm text-teal">Order placed! The seller will process it soon.</div><?php endif; ?>
    <?php if (!empty($success)): ?><div class="mb-5 rounded-lg border border-teal/30 bg-teal-light px-4 py-3 text-sm text-teal"><?= htmlspecialchars($success) ?></div><?php endif; ?>
    <?php if (!empty($error)): ?><div class="mb-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700"><?= htmlspecialchars($error) ?></div><?php endif; ?>
    <section><div class="mb-3"><h2 class="font-display text-xl font-bold text-ink">Order history</h2></div><?php if (empty($orders)): ?><div class="rounded-lg border bg-white p-10 text-center"><p class="text-sm text-gray-500">No orders yet.</p><a href="/shop" class="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-teal hover:underline"><i data-lucide="shopping-bag" class="h-4 w-4"></i>Browse products</a></div><?php else: ?><div class="overflow-hidden rounded-xl border border-gray-200 bg-white"><table id="customerOrdersTable" data-datatable class="w-full text-sm"><thead><tr class="border-b text-left text-xs uppercase text-gray-500"><th class="p-3">Order</th><th class="p-3">Date</th><th class="p-3">Seller</th><th class="p-3">Payment</th><th class="p-3">Total</th><th class="p-3">Status</th><th class="p-3">Tracking</th><th class="p-3">Action</th></tr></thead><tbody>
      <?php foreach ($orders as $order): $styles=['pending'=>'bg-amber-50 text-amber-700','packed'=>'bg-blue-50 text-blue-700','shipped'=>'bg-indigo-50 text-indigo-700','completed'=>'bg-teal-light text-teal','cancelled'=>'bg-gray-100 text-gray-600','refunded'=>'bg-red-50 text-red-600']; ?><tr class="border-b last:border-0"><td class="p-3 font-semibold">#<?= (int)$order['id'] ?></td><td class="p-3 text-gray-500"><?= date('M j, Y g:i A', strtotime($order['created_at'])) ?></td><td class="p-3"><?= htmlspecialchars($order['seller_name']) ?></td><td class="p-3"><?= htmlspecialchars(ucfirst($order['payment_method'])) ?></td><td class="p-3 font-semibold">₱<?= number_format((float)$order['total_amount'],2) ?></td><td class="p-3"><span class="rounded-full px-2.5 py-1 text-xs font-bold <?= $styles[$order['status']] ?? 'bg-gray-100 text-gray-600' ?>"><?= htmlspecialchars(ucfirst($order['status'])) ?></span></td><td class="p-3 text-xs text-gray-500"><?= !empty($order['tracking_number']) ? htmlspecialchars(($order['courier'] ? $order['courier'].' · ' : '').$order['tracking_number']) : '—' ?></td><td class="p-3"><?php if ($order['status']==='pending'): ?><form method="post" action="/orders/<?= (int)$order['id'] ?>/cancel" class="js-confirm-form" data-title="Cancel this order?" data-text="The reserved stock will be returned." data-confirm-text="Yes, cancel order"><button class="inline-flex items-center gap-1 rounded-lg border border-red-300 px-3 py-1.5 text-xs font-bold text-red-600 hover:bg-red-50"><i data-lucide="x-circle" class="h-4 w-4"></i>Cancel</button></form><?php else: ?><span class="text-xs text-gray-400">—</span><?php endif; ?></td></tr><?php endforeach; ?>
      </tbody></table></div><?php endif; ?></section>
  </main>
</div>
