<div class="flex min-h-screen bg-gray-50">
  <?php require __DIR__ . '/../partials/sidebar.php'; ?>
  <main class="flex-1 px-5 py-7 md:px-8">
    <header class="mb-6"><h1 class="font-display text-2xl font-semibold text-gray-900">Write reviews</h1><p class="mt-1 text-sm text-gray-500">Share feedback for products from delivered online orders.</p></header>
    <?php if (!empty($success)): ?><div class="mb-5 rounded-lg border border-teal/30 bg-teal-light px-4 py-3 text-sm text-teal"><?= htmlspecialchars($success) ?></div><?php endif; ?>
    <?php if (empty($items)): ?><div class="rounded-lg border bg-white p-10 text-center"><p class="text-sm text-gray-500">You do not have delivered items ready for review.</p><a href="/orders" class="mt-3 inline-flex items-center gap-1 text-sm font-semibold text-teal hover:underline"><i data-lucide="package" class="h-4 w-4"></i>View my orders</a></div><?php else: ?><div class="overflow-hidden rounded-xl border border-gray-200 bg-white"><table id="customerReviewsTable" data-datatable class="w-full text-sm"><thead><tr class="border-b text-left text-xs uppercase text-gray-500"><th class="p-3">Product</th><th class="p-3">Order</th><th class="p-3">Delivered</th><th class="p-3">Review status</th><th class="p-3">Action</th></tr></thead><tbody>
      <?php foreach ($items as $item): ?><tr class="border-b last:border-0"><td class="p-3"><div class="flex items-center gap-2"><?php if (!empty($item['image_url'])): ?><img src="/<?= htmlspecialchars($item['image_url']) ?>" alt="" class="h-9 w-9 rounded object-cover"><?php endif; ?><div><p class="font-semibold text-ink"><?= htmlspecialchars($item['product_name']) ?></p><p class="text-xs text-gray-500"><?= htmlspecialchars($item['variant_label'] ?: '—') ?></p></div></div></td><td class="p-3">#<?= (int)$item['order_number'] ?></td><td class="p-3 text-gray-500"><?= $item['delivered_at'] ? date('M j, Y', strtotime($item['delivered_at'])) : '—' ?></td><td class="p-3"><?php if (empty($item['review_id'])): ?><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-bold text-amber-700">Not reviewed</span><?php else: ?><span class="inline-flex items-center gap-1 rounded-full bg-teal-light px-2.5 py-1 text-xs font-bold text-teal"><i data-lucide="check" class="h-3.5 w-3.5"></i>Posted</span><?php endif; ?></td><td class="p-3"><?php if (empty($item['review_id'])): ?><a href="/orders/item/<?= (int)$item['id'] ?>/review" class="js-postpurchase-action inline-flex items-center gap-1 rounded-lg border border-brand px-3 py-1.5 text-xs font-bold text-brand hover:bg-brand hover:text-white" data-title="Write a review?" data-text="You can rate this verified purchase and share your feedback."><i data-lucide="star" class="h-4 w-4"></i>Write review</a><?php else: ?><span class="text-xs text-gray-400">Completed</span><?php endif; ?></td></tr><?php endforeach; ?>
      </tbody></table></div><?php endif; ?>
  </main>
</div>
<script>document.addEventListener('DOMContentLoaded',function(){document.querySelectorAll('.js-postpurchase-action').forEach(function(link){link.addEventListener('click',function(event){event.preventDefault();var href=this.href;Swal.fire({title:this.dataset.title,text:this.dataset.text,icon:'question',showCancelButton:true,confirmButtonText:'Continue',cancelButtonText:'Cancel',confirmButtonColor:'#0d9488',reverseButtons:true}).then(function(result){if(result.isConfirmed)window.location.href=href;});});});});</script>
